import type { RoutineDetail } from '@/types/Routine';

export const ROUTINE_DETAILS: Record<string, RoutineDetail> = {
  // 분할 루틴
  'two-split': {
    id: 'two-split',
    title: '2분할 루틴',
    description: '상체/하체를 나누어 주 2회 운동하는 기본적인 분할 루틴',
    category: '분할 루틴',
    difficulty: 'beginner',
    estimatedTime: 60,
    target: '전신',
    exercises: [
      {
        id: 'bench-press',
        name: '벤치프레스',
        category: '가슴',
        sets: 4,
        reps: '8-12회',
        restTime: '2-3분',
        notes: '가슴 근육의 기본 운동',
      },
      {
        id: 'incline-dumbbell-press',
        name: '인클라인 덤벨 프레스',
        category: '가슴',
        sets: 3,
        reps: '10-12회',
        restTime: '2분',
        notes: '상부 가슴 발달',
      },
      {
        id: 'pull-ups',
        name: '턱걸이',
        category: '등',
        sets: 3,
        reps: '8-12회',
        restTime: '2분',
        notes: '등 근육의 기본 운동',
      },
      {
        id: 'barbell-rows',
        name: '바벨 로우',
        category: '등',
        sets: 3,
        reps: '10-12회',
        restTime: '2분',
        notes: '등 두께 발달',
      },
      {
        id: 'overhead-press',
        name: '오버헤드 프레스',
        category: '어깨',
        sets: 3,
        reps: '8-12회',
        restTime: '2분',
        notes: '어깨 근육 발달',
      },
      {
        id: 'bicep-curls',
        name: '바이셉 컬',
        category: '팔',
        sets: 3,
        reps: '12-15회',
        restTime: '1분',
        notes: '이두근 발달',
      },
      {
        id: 'tricep-dips',
        name: '트라이셉 딥스',
        category: '팔',
        sets: 3,
        reps: '10-15회',
        restTime: '1분',
        notes: '삼두근 발달',
      },
    ],
    tips: [
      '상체 운동일 때는 가슴, 등, 어깨, 팔을 모두 운동합니다',
      '하체 운동일 때는 대퇴사두근, 대퇴이두근, 종아리를 운동합니다',
      '주 2회 운동으로 충분한 휴식을 취하세요',
    ],
  },
  'three-split': {
    id: 'three-split',
    title: '3분할 루틴',
    description: '푸시/풀/레그를 나누어 주 3회 운동하는 중급자 루틴',
    category: '분할 루틴',
    difficulty: 'intermediate',
    estimatedTime: 70,
    target: '전신',
    exercises: [
      {
        id: 'bench-press',
        name: '벤치프레스',
        category: '가슴',
        sets: 4,
        reps: '6-10회',
        restTime: '3분',
        notes: '가슴 근육의 기본 운동',
      },
      {
        id: 'incline-barbell-press',
        name: '인클라인 바벨 프레스',
        category: '가슴',
        sets: 3,
        reps: '8-12회',
        restTime: '2-3분',
        notes: '상부 가슴 발달',
      },
      {
        id: 'dumbbell-flyes',
        name: '덤벨 플라이',
        category: '가슴',
        sets: 3,
        reps: '12-15회',
        restTime: '2분',
        notes: '가슴 외측 발달',
      },
      {
        id: 'overhead-press',
        name: '오버헤드 프레스',
        category: '어깨',
        sets: 4,
        reps: '8-12회',
        restTime: '2-3분',
        notes: '어깨 근육 발달',
      },
      {
        id: 'lateral-raises',
        name: '사이드 레터럴 레이즈',
        category: '어깨',
        sets: 3,
        reps: '12-15회',
        restTime: '1-2분',
        notes: '어깨 측면 발달',
      },
      {
        id: 'tricep-dips',
        name: '트라이셉 딥스',
        category: '팔',
        sets: 3,
        reps: '10-15회',
        restTime: '2분',
        notes: '삼두근 발달',
      },
      {
        id: 'skull-crushers',
        name: '스컬 크러셔',
        category: '팔',
        sets: 3,
        reps: '12-15회',
        restTime: '1-2분',
        notes: '삼두근 고립 운동',
      },
    ],
    tips: [
      '푸시 데이는 가슴, 어깨, 삼두근을 운동합니다',
      '풀 데이는 등, 이두근을 운동합니다',
      '레그 데이는 하체 전체를 운동합니다',
      '각 근육군에 충분한 휴식을 제공합니다',
    ],
  },
  chest: {
    id: 'chest',
    title: '가슴 운동 루틴',
    description: '가슴 근육을 집중적으로 발달시키는 전용 루틴',
    category: '부위별 루틴',
    difficulty: 'intermediate',
    estimatedTime: 50,
    target: '가슴',
    exercises: [
      {
        id: 'bench-press',
        name: '벤치프레스',
        category: '가슴',
        sets: 4,
        reps: '8-12회',
        restTime: '3분',
        notes: '가슴 근육의 기본 운동',
      },
      {
        id: 'incline-dumbbell-press',
        name: '인클라인 덤벨 프레스',
        category: '가슴',
        sets: 3,
        reps: '10-12회',
        restTime: '2-3분',
        notes: '상부 가슴 발달',
      },
      {
        id: 'decline-barbell-press',
        name: '디클라인 바벨 프레스',
        category: '가슴',
        sets: 3,
        reps: '10-12회',
        restTime: '2-3분',
        notes: '하부 가슴 발달',
      },
      {
        id: 'dumbbell-flyes',
        name: '덤벨 플라이',
        category: '가슴',
        sets: 3,
        reps: '12-15회',
        restTime: '2분',
        notes: '가슴 외측 발달',
      },
      {
        id: 'cable-crossovers',
        name: '케이블 크로스오버',
        category: '가슴',
        sets: 3,
        reps: '15-20회',
        restTime: '1-2분',
        notes: '가슴 중앙부 발달',
      },
      {
        id: 'push-ups',
        name: '푸시업',
        category: '가슴',
        sets: 3,
        reps: '최대한 많이',
        restTime: '1분',
        notes: '가슴 지구력 향상',
      },
    ],
    tips: [
      '가슴 운동 시 어깨가 앞으로 나가지 않도록 주의하세요',
      '가슴에 집중하여 운동하세요',
      '다양한 각도로 운동하여 균형잡힌 가슴을 만드세요',
    ],
  },
  beginner: {
    id: 'beginner',
    title: '초보자 루틴',
    description: '운동을 처음 시작하는 분들을 위한 기본 루틴',
    category: '난이도별 루틴',
    difficulty: 'beginner',
    estimatedTime: 40,
    target: '전신',
    exercises: [
      {
        id: 'bodyweight-squats',
        name: '스쿼트',
        category: '하체',
        sets: 3,
        reps: '15-20회',
        restTime: '2분',
        notes: '하체의 기본 운동',
      },
      {
        id: 'push-ups',
        name: '푸시업',
        category: '가슴',
        sets: 3,
        reps: '5-15회',
        restTime: '2분',
        notes: '가슴과 팔의 기본 운동',
      },
      {
        id: 'planks',
        name: '플랭크',
        category: '복근',
        sets: 3,
        reps: '30초-1분',
        restTime: '1분',
        notes: '코어 강화',
      },
      {
        id: 'lunges',
        name: '런지',
        category: '하체',
        sets: 3,
        reps: '10-15회 (각 다리)',
        restTime: '2분',
        notes: '하체 균형 발달',
      },
      {
        id: 'superman',
        name: '슈퍼맨',
        category: '등',
        sets: 3,
        reps: '10-15회',
        restTime: '1분',
        notes: '등 근육 강화',
      },
      {
        id: 'wall-sits',
        name: '벽 스쿼트',
        category: '하체',
        sets: 3,
        reps: '30초-1분',
        restTime: '1분',
        notes: '하체 지구력 향상',
      },
    ],
    tips: [
      '올바른 자세를 우선적으로 연습하세요',
      '무리하지 말고 천천히 진행하세요',
      '규칙적으로 운동하는 습관을 만드세요',
      '충분한 휴식을 취하세요',
    ],
  },
  arnold: {
    id: 'arnold',
    title: '아놀드 가슴 루틴',
    description: '아놀드 슈왈제네거의 고전적인 고강도 가슴 루틴',
    category: '유명 보디빌더 루틴',
    difficulty: 'advanced',
    estimatedTime: 70,
    target: '가슴',
    exercises: [
      {
        id: 'bench-press',
        name: '벤치프레스',
        category: '가슴',
        sets: 5,
        reps: '6-20회 (피라미드)',
        restTime: '2-3분',
        notes: '피라미드 방식으로 수행',
      },
      {
        id: 'incline-barbell-press',
        name: '인클라인 바벨 프레스',
        category: '가슴',
        sets: 5,
        reps: '10-15회',
        restTime: '2분',
        notes: '상부 가슴 강조',
      },
      {
        id: 'dumbbell-flyes',
        name: '덤벨 플라이',
        category: '가슴',
        sets: 5,
        reps: '10-15회',
        restTime: '2분',
        notes: '가슴 스트레칭 및 수축',
      },
      {
        id: 'weighted-dips',
        name: '딥스 (웨이트)',
        category: '가슴',
        sets: 5,
        reps: '15회',
        restTime: '2분',
        notes: '디클라인 자극',
      },
    ],
    tips: ['피라미드 방식으로 무게 점진 증가', '각 세트마다 마지막 1~2회 집중해서 수행', '세트 사이 충분히 휴식하기'],
  },

  // 🧠 Dorian Yates – High-Intensity Back Routine
  'dorian-yates': {
    id: 'dorian-yates',
    title: '도리안 예이츠 등 루틴',
    description: 'Dorian Yates의 고강도 1세트 접근법 기반 등 루틴',
    category: '유명 보디빌더 루틴',
    difficulty: 'advanced',
    estimatedTime: 50,
    target: '등',
    exercises: [
      {
        id: 'nautilus-pullover',
        name: '너틸러스 풀오버',
        category: '등',
        sets: 1,
        reps: '8-10회',
        restTime: '2분',
        notes: '랏 전 피로 유발',
      },
      {
        id: 'hammer-strength-pulldown',
        name: '해머풀다운 (언더그립)',
        category: '등',
        sets: 1,
        reps: '8-10회',
        restTime: '2분',
        notes: '언더그립으로 집중',
      },
      {
        id: 'barbell-rows',
        name: '바벨 로우 (Yates 로우)',
        category: '등',
        sets: 1,
        reps: '8-10회',
        restTime: '2분',
        notes: '상체를 평행보다 약간 내려',
      },
      {
        id: 'one-arm-rows',
        name: '원암 로우 머신',
        category: '등',
        sets: 1,
        reps: '8-10회',
        restTime: '2분',
        notes: '집중 수축',
      },
      {
        id: 'seated-cable-rows',
        name: '시티드 케이블 로우',
        category: '등',
        sets: 1,
        reps: '8-10회',
        restTime: '2분',
        notes: '중간 등 두께 강화',
      },
      {
        id: 'deadlift-partial',
        name: '하이퍼익스텐션 또는 데드리프트',
        category: '등',
        sets: 1,
        reps: '10-12회',
        restTime: '2분',
        notes: '하부 등 자극',
      },
    ],
    tips: ['세트당 1세트 집중 HIT 스타일', '모든 운동 전에 웜업 세트 1~2회 권장', '느리고 엄밀한 수축 유지'],
  },

  // 🏋️‍♂️ Chris Bumstead – 5-Day Split
  'cbum-5day': {
    id: 'cbum-5day',
    title: 'Chris Bumstead 5분할 루틴',
    description: 'Chris Bumstead 스타일의 5일 분할 루틴',
    category: '분할 루틴',
    difficulty: 'intermediate',
    estimatedTime: 60,
    target: '전신',
    exercises: [
      {
        id: 'day1-chest',
        name: '가슴 루틴',
        category: '분할',
        sets: 4,
        reps: '8-12회',
        restTime: '1-2분',
        notes: '벤치, 플라이, 케이블 크로스오버',
      },
      {
        id: 'day2-legs',
        name: '하체 루틴',
        category: '분할',
        sets: 4,
        reps: '8-12회',
        restTime: '1-2분',
        notes: '스쿼트, 레그프레스 등',
      },
      {
        id: 'day3-back',
        name: '등 루틴',
        category: '분할',
        sets: 4,
        reps: '8-12회',
        restTime: '1-2분',
        notes: '데드리프트, 로우, 풀업 포함',
      },
      {
        id: 'day4-shoulders',
        name: '어깨 루틴',
        category: '분할',
        sets: 4,
        reps: '8-12회',
        restTime: '1-2분',
        notes: '밀리터리 프레스, 래터럴 레이즈',
      },
      {
        id: 'day5-arms',
        name: '팔 루틴',
        category: '분할',
        sets: 4,
        reps: '10-15회',
        restTime: '1분',
        notes: '이두/삼두 다양한 컬',
      },
    ],
    tips: ['각 부위 주 1회, 복구 고려한 분할', '하루 한 부위 집중 후 휴식', '중간 중량+클린폼 유지 필수'],
  },

  // 🧱 3분할 Push / Pull / Legs 루틴
  'ppl-split': {
    id: 'ppl-split',
    title: 'Push Pull Legs 3분할',
    description: '전신을 3일에 나눠 푸쉬/풀/레그 루틴',
    category: '분할 루틴',
    difficulty: 'intermediate',
    estimatedTime: 50,
    target: '전신',
    exercises: [
      {
        id: 'push',
        name: '푸쉬 데이 (가슴+어깨+삼두)',
        category: '분할',
        sets: 4,
        reps: '8-12회',
        restTime: '1-2분',
        notes: '벤치, 오버헤드 프레스 등',
      },
      {
        id: 'pull',
        name: '풀 데이 (등+이두)',
        category: '분할',
        sets: 4,
        reps: '8-12회',
        restTime: '1-2분',
        notes: '로우, 풀업, 컬 등',
      },
      {
        id: 'legs',
        name: '레그 데이',
        category: '분할',
        sets: 4,
        reps: '8-15회',
        restTime: '2분',
        notes: '스쿼트, 루마니안 데드리프트 포함',
      },
    ],
    tips: ['주 2회 반복 가능 (PPL PPL 루틴)', '풀과 레그 사이 충분한 휴식 확보', '볼륨 조절하며 주당 세트 적절히 유지'],
  },

  // 💪 부위별 루틴 예시: 등
  back: {
    id: 'back',
    title: '집중 등 루틴',
    description: '허리부터 상부 등까지 균형 있게 자극하는 루틴',
    category: '부위별 루틴',
    difficulty: 'intermediate',
    estimatedTime: 45,
    target: '등',
    exercises: [
      {
        id: 'deadlift',
        name: '데드리프트',
        category: '등',
        sets: 4,
        reps: '4-8회',
        restTime: '2-3분',
        notes: '전신 힘 핵심',
      },
      {
        id: 'lat-pulldown',
        name: '랫풀다운',
        category: '등',
        sets: 4,
        reps: '8-12회',
        restTime: '2분',
        notes: '넓은 등 자극',
      },
      {
        id: 'barbell-row',
        name: '바벨로우',
        category: '등',
        sets: 4,
        reps: '8-12회',
        restTime: '2분',
        notes: '두께 강화',
      },
      {
        id: 'face-pull',
        name: '페이스 풀',
        category: '등',
        sets: 3,
        reps: '12-15회',
        restTime: '1-2분',
        notes: '후면 어깨 포함',
      },
      {
        id: 'hyperextension',
        name: '하이퍼익스텐션',
        category: '등/코어',
        sets: 3,
        reps: '12-15회',
        restTime: '1-2분',
        notes: '하부 등 강화',
      },
    ],
    tips: ['볼륨과 강도를 균형 있게 설정', '형태 유지하며 중량 조절'],
  },
};
