import type { RoutineDetail } from '@/types/Routine';

export const ROUTINE_DETAILS: Record<string, RoutineDetail> = {
  // 분할 루틴
  'two-split': {
    id: 'two-split',
    title: '2분할 루틴',
    description: '상체/하체를 나누어 주 2회 운동하는 기본적인 분할 루틴',
    category: '분할 루틴',
    difficulty: 'beginner',
    estimatedTime: 60,
    exercises: [
      {
        id: 'bench-press',
        name: '벤치프레스',
        category: '가슴',
        sets: 4,
        reps: '8-12회',
        restTime: '2-3분',
        notes: '가슴 근육의 기본 운동',
      },
      {
        id: 'incline-dumbbell-press',
        name: '인클라인 덤벨 프레스',
        category: '가슴',
        sets: 3,
        reps: '10-12회',
        restTime: '2분',
        notes: '상부 가슴 발달',
      },
      {
        id: 'pull-ups',
        name: '턱걸이',
        category: '등',
        sets: 3,
        reps: '8-12회',
        restTime: '2분',
        notes: '등 근육의 기본 운동',
      },
      {
        id: 'barbell-rows',
        name: '바벨 로우',
        category: '등',
        sets: 3,
        reps: '10-12회',
        restTime: '2분',
        notes: '등 두께 발달',
      },
      {
        id: 'overhead-press',
        name: '오버헤드 프레스',
        category: '어깨',
        sets: 3,
        reps: '8-12회',
        restTime: '2분',
        notes: '어깨 근육 발달',
      },
      {
        id: 'bicep-curls',
        name: '바이셉 컬',
        category: '팔',
        sets: 3,
        reps: '12-15회',
        restTime: '1분',
        notes: '이두근 발달',
      },
      {
        id: 'tricep-dips',
        name: '트라이셉 딥스',
        category: '팔',
        sets: 3,
        reps: '10-15회',
        restTime: '1분',
        notes: '삼두근 발달',
      },
    ],
    tips: [
      '상체 운동일 때는 가슴, 등, 어깨, 팔을 모두 운동합니다',
      '하체 운동일 때는 대퇴사두근, 대퇴이두근, 종아리를 운동합니다',
      '주 2회 운동으로 충분한 휴식을 취하세요',
    ],
  },
  'three-split': {
    id: 'three-split',
    title: '3분할 루틴',
    description: '푸시/풀/레그를 나누어 주 3회 운동하는 중급자 루틴',
    category: '분할 루틴',
    difficulty: 'intermediate',
    estimatedTime: 70,
    exercises: [
      {
        id: 'bench-press',
        name: '벤치프레스',
        category: '가슴',
        sets: 4,
        reps: '6-10회',
        restTime: '3분',
        notes: '가슴 근육의 기본 운동',
      },
      {
        id: 'incline-barbell-press',
        name: '인클라인 바벨 프레스',
        category: '가슴',
        sets: 3,
        reps: '8-12회',
        restTime: '2-3분',
        notes: '상부 가슴 발달',
      },
      {
        id: 'dumbbell-flyes',
        name: '덤벨 플라이',
        category: '가슴',
        sets: 3,
        reps: '12-15회',
        restTime: '2분',
        notes: '가슴 외측 발달',
      },
      {
        id: 'overhead-press',
        name: '오버헤드 프레스',
        category: '어깨',
        sets: 4,
        reps: '8-12회',
        restTime: '2-3분',
        notes: '어깨 근육 발달',
      },
      {
        id: 'lateral-raises',
        name: '사이드 레터럴 레이즈',
        category: '어깨',
        sets: 3,
        reps: '12-15회',
        restTime: '1-2분',
        notes: '어깨 측면 발달',
      },
      {
        id: 'tricep-dips',
        name: '트라이셉 딥스',
        category: '팔',
        sets: 3,
        reps: '10-15회',
        restTime: '2분',
        notes: '삼두근 발달',
      },
      {
        id: 'skull-crushers',
        name: '스컬 크러셔',
        category: '팔',
        sets: 3,
        reps: '12-15회',
        restTime: '1-2분',
        notes: '삼두근 고립 운동',
      },
    ],
    tips: [
      '푸시 데이는 가슴, 어깨, 삼두근을 운동합니다',
      '풀 데이는 등, 이두근을 운동합니다',
      '레그 데이는 하체 전체를 운동합니다',
      '각 근육군에 충분한 휴식을 제공합니다',
    ],
  },
  chest: {
    id: 'chest',
    title: '가슴 운동 루틴',
    description: '가슴 근육을 집중적으로 발달시키는 전용 루틴',
    category: '부위별 루틴',
    difficulty: 'intermediate',
    estimatedTime: 50,
    exercises: [
      {
        id: 'bench-press',
        name: '벤치프레스',
        category: '가슴',
        sets: 4,
        reps: '8-12회',
        restTime: '3분',
        notes: '가슴 근육의 기본 운동',
      },
      {
        id: 'incline-dumbbell-press',
        name: '인클라인 덤벨 프레스',
        category: '가슴',
        sets: 3,
        reps: '10-12회',
        restTime: '2-3분',
        notes: '상부 가슴 발달',
      },
      {
        id: 'decline-barbell-press',
        name: '디클라인 바벨 프레스',
        category: '가슴',
        sets: 3,
        reps: '10-12회',
        restTime: '2-3분',
        notes: '하부 가슴 발달',
      },
      {
        id: 'dumbbell-flyes',
        name: '덤벨 플라이',
        category: '가슴',
        sets: 3,
        reps: '12-15회',
        restTime: '2분',
        notes: '가슴 외측 발달',
      },
      {
        id: 'cable-crossovers',
        name: '케이블 크로스오버',
        category: '가슴',
        sets: 3,
        reps: '15-20회',
        restTime: '1-2분',
        notes: '가슴 중앙부 발달',
      },
      {
        id: 'push-ups',
        name: '푸시업',
        category: '가슴',
        sets: 3,
        reps: '최대한 많이',
        restTime: '1분',
        notes: '가슴 지구력 향상',
      },
    ],
    tips: [
      '가슴 운동 시 어깨가 앞으로 나가지 않도록 주의하세요',
      '가슴에 집중하여 운동하세요',
      '다양한 각도로 운동하여 균형잡힌 가슴을 만드세요',
    ],
  },
  beginner: {
    id: 'beginner',
    title: '초보자 루틴',
    description: '운동을 처음 시작하는 분들을 위한 기본 루틴',
    category: '난이도별 루틴',
    difficulty: 'beginner',
    estimatedTime: 40,
    exercises: [
      {
        id: 'bodyweight-squats',
        name: '스쿼트',
        category: '하체',
        sets: 3,
        reps: '15-20회',
        restTime: '2분',
        notes: '하체의 기본 운동',
      },
      {
        id: 'push-ups',
        name: '푸시업',
        category: '가슴',
        sets: 3,
        reps: '5-15회',
        restTime: '2분',
        notes: '가슴과 팔의 기본 운동',
      },
      {
        id: 'planks',
        name: '플랭크',
        category: '복근',
        sets: 3,
        reps: '30초-1분',
        restTime: '1분',
        notes: '코어 강화',
      },
      {
        id: 'lunges',
        name: '런지',
        category: '하체',
        sets: 3,
        reps: '10-15회 (각 다리)',
        restTime: '2분',
        notes: '하체 균형 발달',
      },
      {
        id: 'superman',
        name: '슈퍼맨',
        category: '등',
        sets: 3,
        reps: '10-15회',
        restTime: '1분',
        notes: '등 근육 강화',
      },
      {
        id: 'wall-sits',
        name: '벽 스쿼트',
        category: '하체',
        sets: 3,
        reps: '30초-1분',
        restTime: '1분',
        notes: '하체 지구력 향상',
      },
    ],
    tips: [
      '올바른 자세를 우선적으로 연습하세요',
      '무리하지 말고 천천히 진행하세요',
      '규칙적으로 운동하는 습관을 만드세요',
      '충분한 휴식을 취하세요',
    ],
  },
};
